# Generated by Django 3.2.8 on 2021-10-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Not_Working_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Descrição')),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afternoon_entry_time', models.TimeField(blank=True, null=True)),
                ('afternoon_departure_time', models.TimeField(blank=True, null=True)),
                ('morning_entry_time', models.TimeField(blank=True, null=True)),
                ('morning_departure_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('field_title_1', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_2', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_3', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_4', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_5', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_6', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_7', models.CharField(blank=True, max_length=30, null=True)),
                ('field_title_8', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('field_value_1', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_2', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_3', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_4', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_5', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_6', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_7', models.CharField(blank=True, max_length=100, null=True)),
                ('field_value_8', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_working_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.not_working_day')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
                ('titles_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sheet_title')),
                ('values_fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sheet_value')),
            ],
        ),
    ]
