# Generated by Django 3.2.8 on 2021-10-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sheet_values_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='not_working_days',
        ),
        migrations.AddField(
            model_name='not_working_day',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sheet'),
        ),
    ]
