# Generated by Django 3.2.8 on 2021-10-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211026_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not_Work_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, verbose_name='Nome')),
            ],
        ),
        migrations.AlterField(
            model_name='not_working_day',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.not_work_type'),
        ),
    ]
