# Generated by Django 3.2.8 on 2021-10-26 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211026_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet_value',
            name='date',
        ),
        migrations.AddField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
