# Generated by Django 3.2.8 on 2021-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211026_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='img_path',
            field=models.ImageField(blank=True, height_field=2.67, null=True, upload_to='img_sheet', width_field=6.94),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_4',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_5',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_6',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_7',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_title',
            name='field_title_8',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_7',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet_value',
            name='field_value_8',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
