# Generated by Django 3.2.8 on 2021-10-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211027_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
